### ISSUE TITLE
Parameters not sent in custom methods using other method than get

### ISSUE THREAD

**Issue by jdiezf** [chingor13/json_api_client#108]
Hi,

I defined a custom method with put method following the example in the documentation, but the parameters I pass to the method are not introduced in the request. I tried post and patch and it didn't work either.

I've been checking everything without any luck. It looks like the params hash arrive correctly to the call to faraday in https://github.com/chingor13/json_api_client/blob/master/lib/json_api_client/connection.rb#L31, but they don't get inserted in the request.

Currently I don't know if it's a bug or it's only happening to me because of any misconfiguration. Has anyone been able to use a custom method with post, put or patch and pass parameters to the API?

I paste below the affected code:

````
custom_endpoint :rate, on: :member, request_method: :put


i = Item.find(123).first
i.rate(rating: 5)
````

In this case, the API only receives the id parameter with value 123, but not the rating parameter.

I'm working with 1.0.0.beta6.

Thanks in advance

**Comment by chingor13** [comment]
Hmm, this seems like a bug. I'll take a look when I get a chance.

**Comment by jdiezf** [comment]
Great, thanks. I've been troubleshooting it but I didn't find the problem. If you need something from me, just ask.

**Comment by jdiezf** [comment]
Forget it, just found the problem and it wasn't here, it was in the API that wasn't recognizing the MIME type and wasn't parsing the body correctly. Closing...
