### ISSUE TITLE
Trouble populating an object

### ISSUE THREAD

**Issue by adamgotterer** [chingor13/json_api_client#115]
For a lack of a better place to pose the question. I'm having a tough time populating an actual object with a JSON api response. My object is always nil. I hope someone can help...

```ruby
class API < JsonApiClient::Resource
  self.site = ' http://demo5590011.mockable.io/'
  # Result from that URL is: {"meta":{"testing": "someval"},"data":{"id":"79","type":"partner","attributes":{ "something": "somval"}}}
end

class Partner < API

end

p Partner.find(79).first
#> Nil
```

Thanks!

**Comment by chingor13** [comment]
The newest format is in master targeting a 1.0.0 release (which should be very soon). There is a beta gem on rubygems. The only stable releases were an older version of the spec.

**Comment by adamgotterer** [comment]
Thanks, that appears to work.
