### ISSUE TITLE
Unnest some resource routes?

### ISSUE THREAD

**Issue by jramos** [chingor13/json_api_client#118]
When using `belongs_to`, all resources paths are being nested. With our API, though, if you have the ID of an element that you want to save, update or destroy, you use an unnested route. E.g.

`/api/v1/foo/1/bar/1` isn't valid in our API, but
`/api/v1/bar/1` is.

Is there a good way to support this using the gem, having index/create go to the nested route and show/update/destroy go to the unnested route?

**Comment by chingor13** [comment]
Unless you want nested routes, avoid using `belongs_to`. It is only there to set up nested routes.

If there are associated records or links, defined in the jsonapi response, the client can follow those definitions.

**Comment by jramos** [comment]
Is there a way using custom_endpoints to get the desired behavior? Or should I just flatten the structure and use `:relationships` instead of path parameters?
