### ISSUE TITLE
Getters for dasherized attributes in a resource

### ISSUE THREAD

**Issue by theirishpenguin** [chingor13/json_api_client#132]
~~(and setters too?)~~ UPDATE: Doesn't make sense for setters as they already work. Only getters are problematic. 

If I have a server that sends down JSON like the following...

```
{
  "data": [
    {
      "id": "1",
      "type": "super-cars",
      "links": {
        "self": "http://localhost:3000/api/v1/super-cars/1"
      },
      "attributes": {
        "name": "Red Car",
        "engine-name": "V8"
      }
    }
  ]
}
```

Then I can easily access "name" via a method...

```
  some_car.name
  #=> "Red Car"
```

... but I cannot easily access "engine_name"...

```
  some_car.engine_name
  #=> *** NoMethodError Exception: undefined method `engine_name' for #<SuperCar:0x007f8718b7c748>
```

... I can hack it using send()...

```
  some_car.send("engine-name")
  #=> "V8"
```

... but what is the most elegant way to access this?

I would think that calling some_car.engine_name() should return the value.

**Comment by chingor13** [comment]
You should be able to access with brackets. 

some_car["engine-name"] for getting and setting

**Comment by theirishpenguin** [comment]
How about something like this? https://github.com/chingor13/json_api_client/pull/133/files

**Comment by theirishpenguin** [comment]
One issue with the above PR might be setting dasherized attributes. I think json_api_client has no way to know if we want to set "engine-size" or "engine_size".

If a nice getter is exposed to set an attribute then surely a nice setter should be available too.

Perhaps we could have a configuration setting that says whether the json contains dasherized attributes (as recommended by jsonapi.org AFAIK) or underscored attributes (or camel cased, etc but I am less interested in them at the moment)? There is no configuration section for json_api_client at the moment, correct?

**Comment by arthurmde** [comment]
Hey guys,

I have the same issue described here. I liked the solution !133 but it was not merged, unfortunately.
The arguments of @theirishpenguin in this issue and in the PR are right IMHO. 

What if you want to mass-assign the dasherized attributes from JsonApiClient::Resource to a local ActiveRecord model that has the equivalent attribute  underscored names? You can't!

You would have to make a hack to do that, such as the following method in a JsonApiClient::Resource:
```ruby
# Format the JSON-API fields to underscore-based symbols to enable the           
# mass-assignment for building domain model objects.                                      
def formmated_attributes                                                       
  data = {}                                                                    
  attributes.each do |name, value|                                             
    key = name.underscore.to_sym                                               
    data[key] = value                                                          
  end                                                                          
  data
end          
```
