### ISSUE TITLE
Support for extracting http status code from the http response

### ISSUE THREAD

**Issue by theirishpenguin** [chingor13/json_api_client#135]
This could be my lack of understanding but why is the "meta" section of the response inspected in order to extract a http status code. Would it not be more correct to get the status code from the response itself?

https://github.com/chingor13/json_api_client/blob/master/lib/json_api_client/middleware/status.rb#L10

(Perhaps there is a well-known convention of extracting this from the "meta" section of responses that I'm not aware of?)

I can understand extracting http status code from "errors" object in the case of multiple errors occurring in a request (as per http://jsonapi.org/format/#errors).

**Comment by theirishpenguin** [comment]
eg. https://github.com/chingor13/json_api_client/pull/136

**Comment by chingor13** [comment]
We already use the http status on https://github.com/chingor13/json_api_client/blob/master/lib/json_api_client/middleware/status.rb#L6

**Comment by theirishpenguin** [comment]
PR added at https://github.com/chingor13/json_api_client/pull/140
