### ISSUE TITLE
json_decode JSON_BIGINT_AS_STRING PHP 5.5.?

### ISSUE THREAD

**Issue by Mojo1** [chingor13/json_api_client#148]
PHP Warning: json_decode(): option JSON_BIGINT_AS_STRING not implemented
https://bugs.php.net/bug.php?id=63520

art4/json-api-client/src/Utils/Helper.php line 54

maybe this should be workarounded/adopted to be future proof
I am experiencing this with php version 5.5.9 on a debian server - on dev systems it was all good...

**Comment by chingor13** [comment]
I think you filed this in the wrong place - this is a ruby client, not php
