### ISSUE TITLE
connection with rebuild does not work

### ISSUE THREAD

**Issue by garytaylor** [chingor13/json_api_client#151]
Whilst not a documented feature and I have found a solution - I just wanted to let you know that I had found this in case you weren't aware.

The connection method on the Resource class has a "rebuild" parameter.  However, this is not used - I would expect it to be passed to the underlying _build_connection call 

Thanks

**Comment by drock** [comment]
I just ran into this as well and submitted PR #152 with a fix.

**Comment by drock** [comment]
You can temporarily work around this by using _build_connection directly:
```ruby
Base.send(:_build_connection, true) do |conn|
 ...
end
```
