### ISSUE TITLE
Applying Additional Params

### ISSUE THREAD

**Issue by pwgustafson** [chingor13/json_api_client#168]
Is there a way to apply additional URL params to the query?

I am using the `.where(key: 'value')` and I see that puts all the params in the filters hash, but how would I define other params

I need something like:

`api/resource/?filter[key]=value&other_param=test`

How can I get that `other_param` outside of the filter hash?

Thanks!

**Comment by chingor13** [comment]
I got a PR https://github.com/chingor13/json_api_client/pull/160 that is included in the 1.1.0 version. I'll update the README soon. It's `.with_params(other_param: 'test')`

**Comment by pwgustafson** [comment]
Awesome, thanks! :+1:

**Comment by dmbrooking** [comment]
This isn't working for me and I don't know if I am just missing something simple. I have a custom endpoint and have tried both on the member and the collection.

`custom_endpoint :set_billable_status, on: :collection, request_method: :put`
`Model.set_billable_status(id: id).with_params(billable: false)`
and the params available in the api controller are:
`{"format"=>:json, "controller"=>"controller_name", "action"=>"set_billable_status", "id"=>"5"}`

So id is making it, but not billable.

I also did on the member level.
`custom_endpoint :set_billable_status, on: :member, request_method: :put`
`m = Model.find(id: id).first`
`m.set_billable_status(billable: false)`

and again, all I get in params is 
`{"format"=>:json, "controller"=>"controller_name", "action"=>"set_billable_status", "id"=>"5"}`

am I missing something?
