### ISSUE TITLE
Raising exception on 422

### ISSUE THREAD

**Issue by garytaylor** [chingor13/json_api_client#219]
Hi,
  I noticed that there has been a change on 22 september to raise an exception on a 422 error.
I was wondering how this was going to work as at present, when a record is saved and it fails, you can then read the errors of the instance - which then get rendered to the form etc.. by standard rails code - i.e. it operates much like active record.

Surely with this change, we will have to add rescue blocks everywhere ?

Cheers

Gary

**Comment by natemacinnes** [comment]
https://github.com/chingor13/json_api_client/commit/617783d4766d753c0af4afbbf748a834da122472

**Comment by chingor13** [comment]
You're correct, and is being reverted before the next version release. Thanks for catching it.
