### ISSUE TITLE
Display requests and responses?

### ISSUE THREAD

**Issue by JohnSmall** [chingor13/json_api_client#220]
Any idea how I can get it to display the full request and response?

It's doing something wrong when interacting with an API I don't have control over and can't see what's coming through. So I need to see what's being sent.

**Comment by natemacinnes** [comment]
Add this to your base class:

```ruby
   Base.connection do | connection |
        connection.use Faraday::Response::Logger
    end 
```

The above will output the raw request and response text to stdout.

**Comment by JohnSmall** [comment]
Yes, I'd already tried that. It displays the url for the POST/PATCH, but not the body, so it's a bit useless. 

However I got around the problem by following the guidelines on how to get VCR to work in https://github.com/chingor13/json_api_client/issues/171. So I just had to look at the yml files created by VCR to see what was being sent and that solved my problem. So I'll close this,

**Comment by natemacinnes** [comment]
Oh, yeah forgot about that, I ended up using a gem that included bodies and more recently found out that Faraday includes it with a little manipulation:

```Ruby
Faraday.new do |faraday|
  faraday.response :logger, ::Logger.new(STDOUT), bodies: true
end
```
