### ISSUE TITLE
custom_headers overwritten?

### ISSUE THREAD

**Issue by latompa** [chingor13/json_api_client#273]
I have a hard time wrapping my head around this ensure block
https://github.com/chingor13/json_api_client/blob/a42c6fd66a7a64b3f961c8936534d6436d2c9e1b/lib/json_api_client/resource.rb#L151

Is it supposed to read like this?

    self._custom_headers ||= {}

Otherwise, wouldn't custom headers be ignored?

**Comment by chingor13** [comment]
The `with_headers` class method is meant to temporarily set extra headers only within the context of the block provided. The way it's currently implemented, you cannot nest these.

Example:

```ruby
MyResource.with_headers({'X-Foo' => 'Bar'}) do
  # makes a request to /my_resources with a X-Foo=bar header
  MyResource.all
end
```

If we use `self._custom_headers ||= {}`, we wouldn't reset the headers afterwards and it would even leak between requests.

**Comment by latompa** [comment]
makes sense, thank you Jeff!
