### ISSUE TITLE
JsonApiClient::Resource incompatible w/ ActiveModel::Model

### ISSUE THREAD

**Issue by bvandenbos** [chingor13/json_api_client#45]
Including ActiveMode::Model in your resource (for instance, if you want to add client side validation to your resource), overrides `initialize` which breaks JsonApiClient::Resource.

**Comment by bvandenbos** [comment]
One solution might be to to leverage ActiveModel as part of JsonApiClient::Resource

**Comment by Fivell** [comment]
+1

**Comment by senid231** [comment]
+1

**Comment by chingor13** [comment]
I am investigating this in the pangaea branch. I'm also looking into combining the non-shared concerns because keeping the concerns separate was getting extremely difficult as some of the concepts overlap and managing the load order/inheritance chain was becoming a nightmare.

**Comment by chingor13** [comment]
I can't include ActiveModel::Model in resource because that particular concern was not available in 3.2. However, I am including the 4 basic models that concern includes:

* `ActiveModel::Naming`
* `ActiveModel::Translation`
* `ActiveModel::Validations`
* `ActiveModel::Conversion`

**Comment by senid231** [comment]
good job @chingor13 .
we could also include 
* `ActiveModel::Callbacks` instead of `ActiveSupport::Callbacks` 
* `ActiveModel::Dirty` instead of `JsonApiClient::Helpers::Dirty`

**Comment by chingor13** [comment]
I can't actually use `ActiveModel::Dirty` because it requires you to have defined attributes.

**Comment by senid231** [comment]
it doesn't require defined attributes (at least latest versions), but `ActiveModel::Dirty` `v3.2` and `v.4.2`  differs a lot.
i use `v4.2.3` in [senid231/json_api_client/use_active_model_dirty](https://github.com/senid231/json_api_client/tree/use_active_model_dirty) and all tests are passed

**Comment by Fivell** [comment]
@chingor13 , rails 5 are coming , do you really want to support rails3+ ?

**Comment by chingor13** [comment]
For now I do want to support 3.2+ as I know some people that are still on 3.2
