### ISSUE TITLE
PATCH requests (updates) are passing down down the entire "links" blob including self references

### ISSUE THREAD

**Issue by bvandenbos** [chingor13/json_api_client#57]
If you load a resource that contains a "self" link and then attempt and update, the "self" link is passed back to the server which violates the spec (and breaks w/ many server implementations).

**Comment by bvandenbos** [comment]
You can see a hack solution here: https://github.com/bvandenbos/json_api_client/commit/4e46b9503fee418a7183748b57a566a17b40bdee

**Comment by senid231** [comment]
:+1: @bvandenbos 

i also remove read only relationships from ```data```

**Comment by chingor13** [comment]
should be addressed in #84
