### ISSUE TITLE
Dirty tracking to submit minimal PATCH requests?

### ISSUE THREAD

**Issue by bvandenbos** [chingor13/json_api_client#58]
Currently, json_api_client submits the entire attributes hash.  Ideally, it would maintain some dirty tracking and (by default) only submit changed attributes.

**Comment by senid231** [comment]
[(WIP) add_dirty_tracking](https://github.com/senid231/json_api_client/commit/80187c9901cba73a2dc8cacc30af649d6c50fafc)

it's only beginning. 
i think about changing ```attributes``` method behaviour.
it should return only id, type and ```@attributes``` (id and type changings will be restricted). i think ```relationships``` should hash where key is a relation name and value is an instance of something like HasOneRelationship or HasManyRelationship. each of this objects will have its own dirty tracking (type changing will be restricted)
i will allow to do something like:
```ruby
author = Client::Author.includes(:city).find(1).first # or without includes if we will have ability to fetch relations using links in relationships
another_city = Client::City.find(35).first
author.city.id # 33
author.city = another_city # will change id or relationship and replace data in included (if it available)
author.save # will send patch wih body like: {data: {relatiohships: city: {data: id: '35', type: 'cities'}}}
```

@chingor13 , @bvandenbos , what do you think about this?

**Comment by senid231** [comment]
take a look #90

**Comment by senid231** [comment]
PR #90 is merged. at now client have separate dirty tracking for attributes and relationships.
@bvandenbos is it resolve the issue?

**Comment by bvandenbos** [comment]
Yes - it appears to.  Thank you.
