### ISSUE TITLE
pagination format

### ISSUE THREAD

**Issue by Fivell** [chingor13/json_api_client#61]
Hello @chingor13 ,
according to last spec
```
The page query parameter is reserved for pagination.
Servers and clients SHOULD use this key for pagination operations.
```

And

```
For example, a page-based strategy might use query parameters such as page[number] 
and page[size], an offset-based strategy might use page[offset] and page[limit], 
while a cursor-based strategy might use page[cursor].
```

Do you have plans to support it ?

**Comment by chingor13** [comment]
Yes, when I was doing the updates for RC3, there was no guidance/spec for what the pagination params should look like. I didn't have time to actively make changes along with each version. It does look like they just finalized 1.0, so I will get back to working on matching that spec

**Comment by Fivell** [comment]
@chingor13 , sounds good, we all are looking forward for stable 1.0 complied ruby gem
