### ISSUE TITLE
Inject custom headers on resource request?

### ISSUE THREAD

**Issue by klaut** [chingor13/json_api_client#64]
Hi!

I was wondering if it is possible to inject custom headers when a resource makes a request?
Specifically, I am trying to send an authorization token with the headers. I have an api on the other end that upon successful login sends back an auth token and I want my recourse to then inject that token into request headers.
After looking around the source code, I am not sure I can do that. I know I can customize the connection on initialization (as in your examples) but at that time I will not know the token yet, and token is an attribute of a specific resource.

I hope I am making any sense :)
Thank you!

**Comment by klaut** [comment]
For now I am using this ugly initializer in my resource class:

```
      initializer do |obj, params|
        obj.class.connection.faraday.token_auth obj.auth_token
      end
```

**Comment by chingor13** [comment]
What we do for this is to use a custom Faraday middleware. Something like:

```
class MyBaseResource < JsonApiClient::Resource
  class << self
    # make this threadsafe if necessary
    def user
      @user ||= begin
        superclass.user if superclass.respond_to?(:user)
      end
    end

    def user=(user)
      @user = user
    end

    def build_connection
      super.tap do |conn|
        conn.use AuthenticationMiddleware, self
      end
    end

    def as_user(user)
      self.user = user
      yield
    ensure
      self.user = nil
    end
  end
end

class MyMiddleware < Faraday::Middleware
  attr_reader :klass, :app

  def initialize(app, klass)
    super(app)
    @klass = klass
  end

  def call(environment)
    # write whatever custom headers you want
    environment[:request_headers]["X-UserId"] = klass.user.id.to_s if klass.user
    @app.call(environment)
  end
end

MyBaseResource.as_user(user1) do
  resources = MyResource.all
end
```

It's hard to specify headers per request because there are so many possible ways to do initiate a remote server request.

**Comment by Fivell** [comment]
@chingor13, I think there should be one recommended by you way to do this, would be great to have clean DSL with possibility to send per-request thread safe headers

**Comment by senid231** [comment]
[custom_headers](https://github.com/senid231/json_api_client/commit/340619a86b49a2911d8848615a463e120142bfb3)
maybe, something like this?

**Comment by klaut** [comment]
Yeah, something like that :+1:  :)

**Comment by chingor13** [comment]
That would work if the custom headers you want to send are static because it's defined on the class. It wouldn't let you do it on a per request basis.

**Comment by chingor13** [comment]
I also realize that inherently `json_api_client` is not thread-safe because I'm using a class variable for the connection. To make it threadsafe, we'd want to wrap the connection in a connection pool (which I didn't want to implement) or use `Thread.current` for the class variables.

**Comment by Fivell** [comment]
@chingor13 , Thread.current is not an option because it can be reused in other threads in multi-threaded servers (for instance unicorn)

**Comment by klaut** [comment]
Nice job! Thank you @chingor13 :+1:
