### ISSUE TITLE
dasherized keys support?

### ISSUE THREAD

**Issue by sharshenov** [chingor13/json_api_client#65]
As said in [recommendations](http://jsonapi.org/recommendations/#naming)

> Member names SHOULD contain only the characters "a-z" (U+0061 to U+007A), "0-9" (U+0030 to U+0039), and the hyphen minus (U+002D HYPHEN-MINUS, "-") as seperator between multiple words.

JsonApiClient::Resource instances have broken attrs in case of dasherized json keys. Should resource attributes keys be underscored first?

**Comment by chingor13** [comment]
You should just be able to access with:
* `resource["foo-bar"]`
* `resource[:"foo-bar"]`
* `resource.send("foo-bar")`
* `resource.send(:"foo-bar")`

I'll add a test to ensure this is the case.

**Comment by Fivell** [comment]
@chingor13 , what about routes ? 
It is hardcoded to use underscore now 
https://github.com/chingor13/json_api_client/blob/a4465fd1e4457cf0453b06e7d49d5a077d943928/lib/json_api_client/resource.rb#L25 

Thoughts ?
