### ISSUE TITLE
Allow to pick faraday adapter

### ISSUE THREAD

**Issue by sharshenov** [chingor13/json_api_client#69]
I've noticed, that json_api_client uses default faraday adapter based on net/http. The better approach is to allow to define adapter in json_api_client configuration.

Another way is to autodetect available adapters. The elasticsearch-transport gem [tries to detect available custom adapters before picking default one](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/lib/elasticsearch/transport/client.rb#L179).

**Comment by chingor13** [comment]
The resource has built in connection options, so I'm thinking:

```
class MyResource < JsonApiClient::Resource
  self.connection_options = {
    adapter: :net_http_persistent
  }
end
```

**Comment by chingor13** [comment]
Should be able to specify adapter via the connections_options
