### ISSUE TITLE
POST instead of PATCH when updating included object

### ISSUE THREAD

**Issue by senid231** [chingor13/json_api_client#77]
```ruby
class Base < JsonApiClient::Resource
  self.site = 'http://127.0.0.1:3000/'
end

class Author < Base
  has_many :posts
 end

class Post < Base
  belongs_to :author
end
```
when i fetch and update post like this
```ruby
p = Client::Post.where(author_id: 1).find(1).first
p.title = 'qwe'
p.save
```
client sends correct request ```Started PATCH "/authors/1/posts/1"```

but when we trying to do same with included record
```ruby
a = Client::Author.includes(:posts).find(1).first
p = a.posts.first
p.title = 'qwe'
p.save
```
clients sends wrong request ```Started POST "/authors/1/posts"```

**Comment by Fivell** [comment]
@chingor13 ,  looks like the problem is that records in included data should be mark as persisted.

**Comment by Fivell** [comment]
https://github.com/chingor13/json_api_client/blob/master/lib/json_api_client/included_data.rb#L13  
  maybe  ```resource.mark_as_persisted!``` should be place here
