### ISSUE TITLE
do you plan to implement callbacks?

### ISSUE THREAD

**Issue by senid231** [chingor13/json_api_client#95]
i think it will be good to have  ```before_save, after_save, before_destroy, after_destroy```
and use it like this:
```ruby
class Author < BaseResource
  before_save :some_instance_method, if: proc { true }
  after_destroy do
    # some code here
  end
end
```

**Comment by Fivell** [comment]
@senid231 , why not to use ActiveModel::Callbacks ?

**Comment by senid231** [comment]
i decided to use `ActiveSupport::Callbacks` in PR #96 
@Fivell what do you think about it?

**Comment by senid231** [comment]
added in 0d40a7afbf68f963f87a27b1f15ed037d59c3d0b
